version: "3.9"
services:
  Postgres-shilov:
    image: postgres:latest
    environment:
      POSTGRES_USER: "shilov"
      POSTGRES_PASSWORD: "shilov"
    expose:
      - "5444"
    ports:
      - "5444:5444"
    restart: on-failure
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5444